### ISSUE TITLE
Implement navigation drawer

### ISSUE THREAD

**Issue by jordanivy** [webdevatlanta/MemberDirectory#27]
Ref: [https://material-ui.com/components/drawers/](url)

Any suggestions on drawer variant we should use for this app?

**Comment by abrie** [comment]
Why do we need one?

**Comment by jordanivy** [comment]
@gitchrisadams and I were discussing yesterday. We were thinking it might be good to link to the discussion board on Meetup (which is practically buried) and the learning resources app when it's up. There were other ideas for the navigation drawer but those were the most relevant for now.

**Comment by abrie** [comment]
Ok, I'm fine with any of the available drawers...

**Comment by abrie** [comment]
Instead of a drawer I hooked in a Material Design "Menu" component (part of PR #36). This seems sufficient for the present use cases. I think we can close this issue.
